name: task_app
description: タスクスケジューラーアプリ(Flutter製)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  cupertino_icons: ^1.0.0
  googleapis: ^0.56.1
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.2
  google_sign_in: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/google_logo.png
